{
  "name": "BeszelBar",
  "options": {
    "bundleIdPrefix": "com.beszel",
    "bundleShortVersion": "1.0.0",
    "bundleVersion": "1",
    "deploymentTarget": "14.0",
    "xcodeVersion": "15.0",
    "generateEmptyDirectories": true
  },
  "settings": {
    "base": {
      "SWIFT_VERSION": "5.10",
      "MACOSX_DEPLOYMENT_TARGET": "14.0",
      "CODE_SIGN_STYLE": "Automatic",
      "ENABLE_HARDENED_RUNTIME": "NO"
    }
  },
  "targets": {
    "BeszelBar": {
      "type": "application",
      "platform": "macOS",
      "sources": [
        {
          "path": "Sources",
          "type": "group"
        },
        {
          "path": "Resources",
          "type": "group"
        }
      ],
      "settings": {
        "base": {
          "INFOPLIST_FILE": "Resources/Info.plist",
          "PRODUCT_BUNDLE_IDENTIFIER": "com.beszel.BeszelBar",
          "ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon",
          "COMBINE_HIDPI_IMAGES": "YES",
          "LD_RUNPATH_SEARCH_PATHS": [
            "$(inherited)",
            "@executable_path/../Frameworks"
          ]
        }
      },
      "entitlements": {
        "path": "Resources/BeszelBar.entitlements",
        "properties": {
          "com.apple.security.app-sandbox": false
        }
      }
    }
  }
}
